version: 0.0
os: linux
files:
  - source: frontend/index.html
    destination: /var/www/html/
hooks:
  AfterInstall:
    - location: scripts/install_and_reload_nginx.sh
      timeout: 60
      runas: root
